services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: chat-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5400:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    image: backend:latest
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    image: frontend:latest
    ports:
      - 5175:80
    depends_on:
      - backend
